services:
  db:
    image: postgres:18-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_DB: localpaas
      POSTGRES_USER: localpaas
      POSTGRES_PASSWORD: abc123
    ports:
      - "35432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "36379:6379"
    command: redis-server

  redis_ui:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    volumes:
      - redis_ui:/data
    ports:
      - 38001:8001
    links:
      - redis

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "38080:8080"
    links:
      - db

volumes:
  db_data:
    driver: local
  redis:
    driver: local
  redis_ui:
    driver: local
