env: development
platform: local

dev_mode:
  skip_auth_check: false

app:
  name: LocalPaas
  version: 0.1
  base_url: http://localhost # front-end base URL

log:

db:
  host: localhost
  port: 35432
  user: localpaas
  password: abc123
  db_name: localpaas
  max_open_conns: 20
  max_idle_conns: 20
  conn_max_lifetime: 60m
  ssl_mode: disable

cache:
  url: redis://default:abc123@localhost:36379/0
  pool_size: 10
  use_tls: false

http_server:
  base_url: http://localhost:10000 # back-end base URL
  base_path: /api/v1
  port: 10000
  cors:
    allow_origins:
      - "*"

session:
  last_access_update_period: 1m
  basic_auth:
    username: admin
    password: abc123
  jwt:
    secret: abc123
    access_token_exp: 12h
    refresh_token_exp: 24h
  mfa:
    passcode_timeout: 60s
    device_trusted_period: 48h # 2-days
