env = "development"
platform = "local"
name = "LocalPaaS"
version = 1
base_url = "http://localhost" # dashboard base URL
secret = "abc123"
app_path = ".appdata"

[db]
    host = "localhost"
    port = 35432
    user = "localpaas"
    password = "abc123"
    db_name = "localpaas"
    ssl_mode = "disable"

[cache]
    url = "redis://default:abc123@localhost:36379/0"
    use_tls = false

[http_server]
    cors_allow_origins = ["*"]

[session]
    last_access_update_period = "1m"
    passcode_timeout = "60s"
    device_trusted_period = "48h" # 2-days

    jwt_secret = "abc123"
    access_token_exp = "12h"
    refresh_token_exp = "24h"

    basic_auth_username = "localpaas"
    basic_auth_password = "abc123"

[ssl]
    le_user_email = "tiendc.lp@gmail.com"
